Feature comments
desyatov-student/java-explore-with-me pull request #3
Opened 2024-11-01 21:07 UTC by desyatov-student

2024-11-01 21:16 UTC, desyatov-student commented
Фикс постман тестов сделали ([ссылка](https://github.com/yandex-praktikum/java-explore-with-me/commit/49becee57ba079144eca8339555c7877cb38f84f) на комит), но только для одной ветки и поэтому для веток с фичей 1 тест так же падает. Я повторно написал чтобы поправили везде

<img width="809" alt="image" src="https://github.com/user-attachments/assets/218a059d-5c08-450f-a706-39f30391e11f">

2024-11-02 13:59 UTC, tomattman requested changes
пара мелочей есть, но основная проблема - то что билд не прошел, тесты упали

2024-11-02 13:59 UTC, tomattman commented on service/src/main/java/ru/practicum/ewm/comment/service/CommentService.java
> +    public List<CommentDto> getAuthorComments(Long authorId, GetCommentsRequest request) {
Лучше переименовать в getCommentByAuthor
пока что не очень внятное имя

2024-11-02 13:59 UTC, tomattman commented on service/src/main/java/ru/practicum/ewm/comment/service/CommentService.java
> +    public List<CommentDto> getEventComments(Long eventId, GetCommentsRequest request) {
аналогично getCommentByEvent

хорошая структура - что делаем с чем делаем по какому признаку делаем

2024-11-02 15:22 UTC, desyatov-student commented on service/src/main/java/ru/practicum/ewm/comment/service/CommentService.java
> +    public List<CommentDto> getEventComments(Long eventId, GetCommentsRequest request) {
Исправил

2024-11-02 15:22 UTC, desyatov-student commented on service/src/main/java/ru/practicum/ewm/comment/service/CommentService.java
> +    public List<CommentDto> getAuthorComments(Long authorId, GetCommentsRequest request) {
Исправил

2024-11-03 09:52 UTC, tomattman approved these changes
Принято

2024-11-12 15:26 UTC, merged